//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioPort.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarioPort.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BLOCK_000 {
            get {
                object obj = ResourceManager.GetObject("BLOCK_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BLOCK_001 {
            get {
                object obj = ResourceManager.GetObject("BLOCK_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK0_000 {
            get {
                object obj = ResourceManager.GetObject("BRICK0_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK0_001 {
            get {
                object obj = ResourceManager.GetObject("BRICK0_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK0_002 {
            get {
                object obj = ResourceManager.GetObject("BRICK0_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK1_000 {
            get {
                object obj = ResourceManager.GetObject("BRICK1_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK1_001 {
            get {
                object obj = ResourceManager.GetObject("BRICK1_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK1_002 {
            get {
                object obj = ResourceManager.GetObject("BRICK1_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK2_000 {
            get {
                object obj = ResourceManager.GetObject("BRICK2_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK2_001 {
            get {
                object obj = ResourceManager.GetObject("BRICK2_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BRICK2_002 {
            get {
                object obj = ResourceManager.GetObject("BRICK2_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BROWN_000 {
            get {
                object obj = ResourceManager.GetObject("BROWN_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BROWN_001 {
            get {
                object obj = ResourceManager.GetObject("BROWN_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BROWN_002 {
            get {
                object obj = ResourceManager.GetObject("BROWN_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BROWN_003 {
            get {
                object obj = ResourceManager.GetObject("BROWN_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BROWN_004 {
            get {
                object obj = ResourceManager.GetObject("BROWN_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHAMP_000 {
            get {
                object obj = ResourceManager.GetObject("CHAMP_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHIBIBO_000 {
            get {
                object obj = ResourceManager.GetObject("CHIBIBO_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHIBIBO_001 {
            get {
                object obj = ResourceManager.GetObject("CHIBIBO_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHIBIBO_002 {
            get {
                object obj = ResourceManager.GetObject("CHIBIBO_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHIBIBO_003 {
            get {
                object obj = ResourceManager.GetObject("CHIBIBO_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap COIN_000 {
            get {
                object obj = ResourceManager.GetObject("COIN_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DES_000 {
            get {
                object obj = ResourceManager.GetObject("DES_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DES_001 {
            get {
                object obj = ResourceManager.GetObject("DES_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DES_002 {
            get {
                object obj = ResourceManager.GetObject("DES_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DES_003 {
            get {
                object obj = ResourceManager.GetObject("DES_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DES_004 {
            get {
                object obj = ResourceManager.GetObject("DES_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DONUT_000 {
            get {
                object obj = ResourceManager.GetObject("DONUT_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DONUT_001 {
            get {
                object obj = ResourceManager.GetObject("DONUT_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXIT_000 {
            get {
                object obj = ResourceManager.GetObject("EXIT_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXIT_001 {
            get {
                object obj = ResourceManager.GetObject("EXIT_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_000 {
            get {
                object obj = ResourceManager.GetObject("F_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_001 {
            get {
                object obj = ResourceManager.GetObject("F_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_002 {
            get {
                object obj = ResourceManager.GetObject("F_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_003 {
            get {
                object obj = ResourceManager.GetObject("F_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FALL_000 {
            get {
                object obj = ResourceManager.GetObject("FALL_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FALL_001 {
            get {
                object obj = ResourceManager.GetObject("FALL_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FENCE_000 {
            get {
                object obj = ResourceManager.GetObject("FENCE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FENCE_001 {
            get {
                object obj = ResourceManager.GetObject("FENCE_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIRE_000 {
            get {
                object obj = ResourceManager.GetObject("FIRE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIRE_001 {
            get {
                object obj = ResourceManager.GetObject("FIRE_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_000 {
            get {
                object obj = ResourceManager.GetObject("FISH_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_001 {
            get {
                object obj = ResourceManager.GetObject("FISH_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FJLUI_000 {
            get {
                object obj = ResourceManager.GetObject("FJLUI_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FJLUI_001 {
            get {
                object obj = ResourceManager.GetObject("FJLUI_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FJMAR_000 {
            get {
                object obj = ResourceManager.GetObject("FJMAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FJMAR_001 {
            get {
                object obj = ResourceManager.GetObject("FJMAR_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FLOWER_000 {
            get {
                object obj = ResourceManager.GetObject("FLOWER_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FWLUI_000 {
            get {
                object obj = ResourceManager.GetObject("FWLUI_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FWLUI_001 {
            get {
                object obj = ResourceManager.GetObject("FWLUI_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FWMAR_000 {
            get {
                object obj = ResourceManager.GetObject("FWMAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FWMAR_001 {
            get {
                object obj = ResourceManager.GetObject("FWMAR_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS_000 {
            get {
                object obj = ResourceManager.GetObject("GRASS_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS_001 {
            get {
                object obj = ResourceManager.GetObject("GRASS_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS_002 {
            get {
                object obj = ResourceManager.GetObject("GRASS_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS_003 {
            get {
                object obj = ResourceManager.GetObject("GRASS_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS_004 {
            get {
                object obj = ResourceManager.GetObject("GRASS_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS1_000 {
            get {
                object obj = ResourceManager.GetObject("GRASS1_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS1_001 {
            get {
                object obj = ResourceManager.GetObject("GRASS1_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS1_002 {
            get {
                object obj = ResourceManager.GetObject("GRASS1_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS2_000 {
            get {
                object obj = ResourceManager.GetObject("GRASS2_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS2_001 {
            get {
                object obj = ResourceManager.GetObject("GRASS2_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS2_002 {
            get {
                object obj = ResourceManager.GetObject("GRASS2_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS3_000 {
            get {
                object obj = ResourceManager.GetObject("GRASS3_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS3_001 {
            get {
                object obj = ResourceManager.GetObject("GRASS3_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRASS3_002 {
            get {
                object obj = ResourceManager.GetObject("GRASS3_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GREEN_000 {
            get {
                object obj = ResourceManager.GetObject("GREEN_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GREEN_001 {
            get {
                object obj = ResourceManager.GetObject("GREEN_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GREEN_002 {
            get {
                object obj = ResourceManager.GetObject("GREEN_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GREEN_003 {
            get {
                object obj = ResourceManager.GetObject("GREEN_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GREEN_004 {
            get {
                object obj = ResourceManager.GetObject("GREEN_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRKOOPA_000 {
            get {
                object obj = ResourceManager.GetObject("GRKOOPA_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRKOOPA_001 {
            get {
                object obj = ResourceManager.GetObject("GRKOOPA_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRKP_000 {
            get {
                object obj = ResourceManager.GetObject("GRKP_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GRKP_001 {
            get {
                object obj = ResourceManager.GetObject("GRKP_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GROUND_000 {
            get {
                object obj = ResourceManager.GetObject("GROUND_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GROUND_001 {
            get {
                object obj = ResourceManager.GetObject("GROUND_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GROUND_002 {
            get {
                object obj = ResourceManager.GetObject("GROUND_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GROUND_003 {
            get {
                object obj = ResourceManager.GetObject("GROUND_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GROUND_004 {
            get {
                object obj = ResourceManager.GetObject("GROUND_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HIT_000 {
            get {
                object obj = ResourceManager.GetObject("HIT_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTRO_000 {
            get {
                object obj = ResourceManager.GetObject("INTRO_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTRO_001 {
            get {
                object obj = ResourceManager.GetObject("INTRO_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTRO_002 {
            get {
                object obj = ResourceManager.GetObject("INTRO_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA_000 {
            get {
                object obj = ResourceManager.GetObject("LAVA_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA_001 {
            get {
                object obj = ResourceManager.GetObject("LAVA_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA2_000 {
            get {
                object obj = ResourceManager.GetObject("LAVA2_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA2_001 {
            get {
                object obj = ResourceManager.GetObject("LAVA2_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA2_002 {
            get {
                object obj = ResourceManager.GetObject("LAVA2_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA2_003 {
            get {
                object obj = ResourceManager.GetObject("LAVA2_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA2_004 {
            get {
                object obj = ResourceManager.GetObject("LAVA2_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LAVA2_005 {
            get {
                object obj = ResourceManager.GetObject("LAVA2_005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LIFE_000 {
            get {
                object obj = ResourceManager.GetObject("LIFE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LIFT1_000 {
            get {
                object obj = ResourceManager.GetObject("LIFT1_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LJLUI_000 {
            get {
                object obj = ResourceManager.GetObject("LJLUI_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LJLUI_001 {
            get {
                object obj = ResourceManager.GetObject("LJLUI_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LJMAR_000 {
            get {
                object obj = ResourceManager.GetObject("LJMAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LJMAR_001 {
            get {
                object obj = ResourceManager.GetObject("LJMAR_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LWLUI_000 {
            get {
                object obj = ResourceManager.GetObject("LWLUI_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LWLUI_001 {
            get {
                object obj = ResourceManager.GetObject("LWLUI_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LWMAR_000 {
            get {
                object obj = ResourceManager.GetObject("LWMAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LWMAR_001 {
            get {
                object obj = ResourceManager.GetObject("LWMAR_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NOTE_000 {
            get {
                object obj = ResourceManager.GetObject("NOTE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALBRICK_000 {
            get {
                object obj = ResourceManager.GetObject("PALBRICK_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM0_000 {
            get {
                object obj = ResourceManager.GetObject("PALM0_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM0_001 {
            get {
                object obj = ResourceManager.GetObject("PALM0_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM0_002 {
            get {
                object obj = ResourceManager.GetObject("PALM0_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM1_000 {
            get {
                object obj = ResourceManager.GetObject("PALM1_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM1_001 {
            get {
                object obj = ResourceManager.GetObject("PALM1_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM1_002 {
            get {
                object obj = ResourceManager.GetObject("PALM1_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM2_000 {
            get {
                object obj = ResourceManager.GetObject("PALM2_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM2_001 {
            get {
                object obj = ResourceManager.GetObject("PALM2_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM2_002 {
            get {
                object obj = ResourceManager.GetObject("PALM2_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM3_000 {
            get {
                object obj = ResourceManager.GetObject("PALM3_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM3_001 {
            get {
                object obj = ResourceManager.GetObject("PALM3_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALM3_002 {
            get {
                object obj = ResourceManager.GetObject("PALM3_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALPILL_000 {
            get {
                object obj = ResourceManager.GetObject("PALPILL_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALPILL_001 {
            get {
                object obj = ResourceManager.GetObject("PALPILL_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PALPILL_002 {
            get {
                object obj = ResourceManager.GetObject("PALPILL_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PART_000 {
            get {
                object obj = ResourceManager.GetObject("PART_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIN_000 {
            get {
                object obj = ResourceManager.GetObject("PIN_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_000 {
            get {
                object obj = ResourceManager.GetObject("PIPE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_001 {
            get {
                object obj = ResourceManager.GetObject("PIPE_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_002 {
            get {
                object obj = ResourceManager.GetObject("PIPE_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_003 {
            get {
                object obj = ResourceManager.GetObject("PIPE_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap POISON_000 {
            get {
                object obj = ResourceManager.GetObject("POISON_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PPLANT_000 {
            get {
                object obj = ResourceManager.GetObject("PPLANT_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PPLANT_001 {
            get {
                object obj = ResourceManager.GetObject("PPLANT_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PPLANT_002 {
            get {
                object obj = ResourceManager.GetObject("PPLANT_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PPLANT_003 {
            get {
                object obj = ResourceManager.GetObject("PPLANT_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QUEST_000 {
            get {
                object obj = ResourceManager.GetObject("QUEST_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QUEST_001 {
            get {
                object obj = ResourceManager.GetObject("QUEST_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RDKOOPA_000 {
            get {
                object obj = ResourceManager.GetObject("RDKOOPA_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RDKOOPA_001 {
            get {
                object obj = ResourceManager.GetObject("RDKOOPA_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RDKP_000 {
            get {
                object obj = ResourceManager.GetObject("RDKP_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RDKP_001 {
            get {
                object obj = ResourceManager.GetObject("RDKP_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RED_000 {
            get {
                object obj = ResourceManager.GetObject("RED_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RED_001 {
            get {
                object obj = ResourceManager.GetObject("RED_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAND_000 {
            get {
                object obj = ResourceManager.GetObject("SAND_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAND_001 {
            get {
                object obj = ResourceManager.GetObject("SAND_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAND_002 {
            get {
                object obj = ResourceManager.GetObject("SAND_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAND_003 {
            get {
                object obj = ResourceManager.GetObject("SAND_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAND_004 {
            get {
                object obj = ResourceManager.GetObject("SAND_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SJLUI_000 {
            get {
                object obj = ResourceManager.GetObject("SJLUI_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SJLUI_001 {
            get {
                object obj = ResourceManager.GetObject("SJLUI_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SJMAR_000 {
            get {
                object obj = ResourceManager.GetObject("SJMAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SJMAR_001 {
            get {
                object obj = ResourceManager.GetObject("SJMAR_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SMTREE_000 {
            get {
                object obj = ResourceManager.GetObject("SMTREE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SMTREE_001 {
            get {
                object obj = ResourceManager.GetObject("SMTREE_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STAR_000 {
            get {
                object obj = ResourceManager.GetObject("STAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap START_000 {
            get {
                object obj = ResourceManager.GetObject("START_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap START_001 {
            get {
                object obj = ResourceManager.GetObject("START_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWLUI_000 {
            get {
                object obj = ResourceManager.GetObject("SWLUI_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWLUI_001 {
            get {
                object obj = ResourceManager.GetObject("SWLUI_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWMAR_000 {
            get {
                object obj = ResourceManager.GetObject("SWMAR_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWMAR_001 {
            get {
                object obj = ResourceManager.GetObject("SWMAR_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TREE_000 {
            get {
                object obj = ResourceManager.GetObject("TREE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TREE_001 {
            get {
                object obj = ResourceManager.GetObject("TREE_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TREE_002 {
            get {
                object obj = ResourceManager.GetObject("TREE_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TREE_003 {
            get {
                object obj = ResourceManager.GetObject("TREE_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WHFIRE_000 {
            get {
                object obj = ResourceManager.GetObject("WHFIRE_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WHHIT_000 {
            get {
                object obj = ResourceManager.GetObject("WHHIT_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WINDOW_000 {
            get {
                object obj = ResourceManager.GetObject("WINDOW_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WINDOW_001 {
            get {
                object obj = ResourceManager.GetObject("WINDOW_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WOOD_000 {
            get {
                object obj = ResourceManager.GetObject("WOOD_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WPALM_000 {
            get {
                object obj = ResourceManager.GetObject("WPALM_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XBLOCK_000 {
            get {
                object obj = ResourceManager.GetObject("XBLOCK_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
